"""
app.py — Chat screen: ChatGPT-style UI for generating test cases from Jira tickets.
"""
from pathlib import Path

import streamlit as st

from config_store import load_config
from jira_client import fetch_ticket, parse_ticket_key
from llm_client import generate

st.set_page_config(page_title="Jira Test Case Generator", page_icon="🧪")
st.title("🧪 Jira Test Case Generator")

# --- Sidebar status ---
cfg = load_config()
with st.sidebar:
    st.markdown("### Status")
    provider = cfg.get("provider", "ollama")
    if provider == "groq":
        st.caption(f"**Provider:** ☁️ GROQ")
        st.caption(f"**Model:** llama-3.3-70b-versatile")
    else:
        st.caption(f"**Provider:** 🖥️ OLLAMA")
        st.caption(f"**Model:** {cfg.get('ollama_model', 'gemma')}")
    st.caption(f"**Jira:** {'✅ Connected' if cfg.get('jira_token') else '❌ Not set'}")
    st.caption(f"**Groq:** {'✅ Ready' if cfg.get('groq_key') else '❌ Not set'}")

    if not cfg.get("jira_token"):
        st.warning("⚠️ Configure Jira credentials in the Settings page first.")

st.divider()

# --- Template loader ---
TEMPLATE_PATH = Path(__file__).parent / "templates" / "TestGen.md"


def load_template() -> str:
    """Load the test case template from disk."""
    if TEMPLATE_PATH.exists():
        return TEMPLATE_PATH.read_text(encoding="utf-8")
    return ""


def build_prompt(ticket: dict, template: str) -> str:
    """Merge ticket data into the template."""
    requirements = f"""Summary: {ticket['summary']}

Description:
{ticket['description']}

Acceptance Criteria:
{ticket.get('acceptance_criteria', 'Not specified')}"""

    prompt = template.replace("[PASTE REQUIREMENTS HERE]", requirements)
    prompt = prompt.replace("[FEATURE]", ticket["summary"])
    prompt = prompt.replace("[NUMBER]", "5")
    return prompt


# --- Session state for messages ---
if "messages" not in st.session_state:
    st.session_state.messages = []

# --- Render chat history ---
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# --- Chat input ---
user_input = st.chat_input("e.g. create test cases for QA-102")

if user_input:
    # Show user message
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

    ticket_key = parse_ticket_key(user_input)

    if not ticket_key:
        error_msg = ("❌ No Jira ticket key found in your message. "
                     "Please include something like `QA-102` or `PROJ-1234`.")
        st.session_state.messages.append({"role": "assistant", "content": error_msg})
        with st.chat_message("assistant"):
            st.markdown(error_msg)
    else:
        # Process the request
        with st.chat_message("assistant"):
            with st.spinner(f"🔍 Fetching ticket **{ticket_key}** from Jira..."):
                try:
                    ticket = fetch_ticket(ticket_key)
                    st.success(f"✅ Ticket **{ticket_key}** — *{ticket['summary']}*")
                except Exception as e:
                    err = f"❌ Failed to fetch {ticket_key}: {e}"
                    st.error(err)
                    st.session_state.messages.append({"role": "assistant", "content": err})
                    st.stop()

            with st.spinner("📝 Loading test case template..."):
                template = load_template()

            with st.spinner("🤖 Generating test cases with LLM..."):
                prompt = build_prompt(ticket, template)
                try:
                    result, actual_provider, model_used = generate(prompt)
                    # Show which provider was used
                    badge_icon = "☁️" if "groq" in actual_provider else "🖥️"
                    st.caption(f"{badge_icon} Generated by **{actual_provider}** ({model_used})")
                    st.markdown(result)
                    st.session_state.messages.append({"role": "assistant", "content": result})
                except Exception as e:
                    err = f"❌ LLM generation failed: {e}"
                    st.error(err)
                    st.session_state.messages.append({"role": "assistant", "content": err})
